# Fetching the minified node image on apline linux
FROM node:slim

# Declaring env
ENV NODE_ENV development

RUN apt-get update && apt-get install curl gnupg -y \
  && curl --location --silent https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
  && apt-get update \
  && apt-get install google-chrome-stable -y --no-install-recommends \
  && apt-get -y install fonts-taml \
  && rm -rf /var/lib/apt/lists/*

# Setting up the work directory
WORKDIR /express-docker

# Copying all the files in our project
COPY . .

# Installing dependencies
RUN npm install

RUN npx puppeteer browsers install chrome


# Starting our application
CMD [ "node", "server.js" ]

# Exposing server port
EXPOSE 3001