# Fetching the minified node image on apline linux
FROM node:slim

# Declaring env
ENV NODE_ENV development

RUN apt-get install -y \
fonts-liberation    \
gconf-service    \
libappindicator1    \
libasound2  \
libatk1.0-0 \
libcairo2   \
libcups2    \
libfontconfig1  \
libgbm-dev  \
libgdk-pixbuf2.0-0  \
libgtk-3-0  \
libicu-dev  \
libjpeg-dev \
libnspr4    \
libnss3     \
libpango-1.0-0  \
libpangocairo-1.0-0 \
libpng-dev  \
libx11-6    \
libx11-xcb1 \
libxcb1 \
libxcomposite1  \
libxcursor1 \
libxdamage1 \
libxext6    \
libxfixes3  \
libxi6  \
libxrandr2  \
libxrender1 \
libxss1 \
libxtst6    \
xdg-utils   

# Setting up the work directory
WORKDIR /express-docker

# Copying all the files in our project
COPY . .

# Installing dependencies
RUN npm install

RUN npx puppeteer browsers install chrome

RUN apt-get install libgtk2.0-0:i386 libsm6:i386

# Starting our application
CMD [ "node", "server.js" ]

# Exposing server port
EXPOSE 3001